In [39]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [40]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,Flatten,MaxPooling2D,Dropout
from tensorflow.keras.utils import to_categorical

In [42]:
df=pd.read_csv('mnist_train.csv')

In [43]:
df_test=pd.read_csv('mnist_test.csv')

In [44]:
df.head()  # pixels of the image

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
df_test.head()   # pixels of training data

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
df.shape

(60000, 785)

In [47]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [48]:
# preprocessing

In [49]:
X_train=df.drop('label',axis=1)
y_train=df['label']

In [50]:
X_test=df_test.drop('label',axis=1)
y_test=df_test['label']

In [51]:
# there are values netween 0 to 255    convert thoose values between 0 and 1

In [52]:
X_train=X_train.astype('float32')/255

In [53]:

X_test=X_test.astype('float32')/255

In [68]:

print(X_train.shape)
print(X_test.shape)

(60000, 784)
(10000, 784)

In [62]:
# reshape the data

In [65]:
X_train_img = X_train.values.reshape(-1, 28, 28)
X_test_img = X_test.values.reshape(-1, 28, 28)

In [66]:
# Each row of 784 numbers is rearranged into a 28×28 image. 
# in the place of -1 u can use 60000 or 10000 as well

In [67]:
df['label'].unique()

array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8])

In [71]:
y_test_cat=to_categorical(y_test,10)  # total 10  labels are presented in the label thast why

In [72]:
y_train_cat=to_categorical(y_train,10)

In [73]:
perceptron=Sequential([
    Flatten(input_shape=(28,28)),
    Dense(10,activation='softmax')])

In [74]:
  # here we created two layers 
# first layer by flatten as 785 inputs in the shape of 28*28 
# second as output layer for 20 labels and activation function of softmax

In [75]:
perceptron.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [78]:
history=perceptron.fit(X_train_img,y_train_cat,batch_size=30,epochs=10,verbose=1,validation_data=[X_test_img,y_test_cat])

Epoch 1/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8774 - loss: 0.4638 - val_accuracy: 0.9141 - val_loss: 0.3086
Epoch 2/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9157 - loss: 0.3023 - val_accuracy: 0.9217 - val_loss: 0.2844
Epoch 3/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9211 - loss: 0.2824 - val_accuracy: 0.9220 - val_loss: 0.2736
Epoch 4/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9245 - loss: 0.2723 - val_accuracy: 0.9239 - val_loss: 0.2709
Epoch 5/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9258 - loss: 0.2661 - val_accuracy: 0.9267 - val_loss: 0.2653
Epoch 6/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9276 - loss: 0.2617 - val_accuracy: 0.9249 - val_loss: 0.2657
Epoch 7/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9278 - loss: 0.2580 - val_accuracy: 0.9252 - val_loss: 0.2663
Epoch 8/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9292 - loss: 0.2549 - val_accuracy: 0.9266 - val_loss: 0.2654
Epoch 9/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9300 - loss: 0.2530 - val_accuracy: 0.9269 - val_loss: 0.2653
Epoch 10/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9314 - loss: 0.2510 - val_accuracy: 0.9271 - val_loss: 0.2658

# Why do we use validation?

# During training, the model learns from the training data. If you only look at training accuracy, the model might simply memorize the training set (overfitting).

In [80]:
loss,acc=perceptron.evaluate(X_test_img,y_test_cat,verbose=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9271 - loss: 0.2658

In [85]:
# now ann using

In [87]:
model=Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128,activation='relu'),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(10,activation='softmax')])

In [88]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [89]:
history1=model.fit(X_train_img,y_train_cat,batch_size=32,epochs=10,verbose=1,validation_data=[X_test_img,y_test_cat])

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9265 - loss: 0.2479 - val_accuracy: 0.9619 - val_loss: 0.1179
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9679 - loss: 0.1053 - val_accuracy: 0.9696 - val_loss: 0.0979
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9766 - loss: 0.0747 - val_accuracy: 0.9733 - val_loss: 0.0895
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9819 - loss: 0.0574 - val_accuracy: 0.9755 - val_loss: 0.0844
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9839 - loss: 0.0482 - val_accuracy: 0.9783 - val_loss: 0.0776
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9867 - loss: 0.0418 - val_accuracy: 0.9781 - val_loss: 0.0794
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9898 - loss: 0.0311 - val_accuracy: 0.9772 - val_loss: 0.0982
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9901 - loss: 0.0304 - val_accuracy: 0.9792 - val_loss: 0.0841
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9915 - loss: 0.0264 - val_accuracy: 0.9778 - val_loss: 0.0827
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9926 - loss: 0.0223 - val_accuracy: 0.9793 - val_loss: 0.0929

In [91]:
acc=model.evaluate(X_test_img,y_test_cat,verbose=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9793 - loss: 0.0929

In [92]:
# CNN

In [95]:
X_train_cnn=X_train.values.reshape(-1,28,28,1)
X_test_cnn=X_test.values.reshape(-1,28,28,1)

In [96]:
# here the last 1 is callles channel colour 
# if it is 1  used for  black and white 
# if it is 3 then used for red green blue (RGB)

In [105]:
cnn=Sequential([
    Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64,kernel_size=(3,3),activation='relu'),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense(120,activation='relu'),
    Dropout(0.5),                      # to protect from overfitting 
    Dense(10,activation='softmax')])

In [106]:
cnn.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [107]:
history=cnn.fit(X_train_cnn,y_train_cat,batch_size=30,epochs=10,verbose=1,validation_data=[X_test_cnn,y_test_cat])

Epoch 1/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9356 - loss: 0.2082 - val_accuracy: 0.9820 - val_loss: 0.0554
Epoch 2/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9754 - loss: 0.0819 - val_accuracy: 0.9888 - val_loss: 0.0339
Epoch 3/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9827 - loss: 0.0605 - val_accuracy: 0.9896 - val_loss: 0.0338
Epoch 4/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9849 - loss: 0.0496 - val_accuracy: 0.9909 - val_loss: 0.0301
Epoch 5/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9877 - loss: 0.0393 - val_accuracy: 0.9905 - val_loss: 0.0284
Epoch 6/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9894 - loss: 0.0354 - val_accuracy: 0.9905 - val_loss: 0.0325
Epoch 7/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9903 - loss: 0.0308 - val_accuracy: 0.9912 - val_loss: 0.0311
Epoch 8/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9914 - loss: 0.0286 - val_accuracy: 0.9927 - val_loss: 0.0249
Epoch 9/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9926 - loss: 0.0233 - val_accuracy: 0.9919 - val_loss: 0.0254
Epoch 10/10
2000/2000 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9934 - loss: 0.0207 - val_accuracy: 0.9918 - val_loss: 0.0318

In [108]:
acc=cnn.evaluate(X_test_cnn,y_test_cat,verbose=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9918 - loss: 0.0318